### ISSUE TITLE
Not in central maven?

### ISSUE THREAD

**Issue by iamthiago** [kamon-io/kamon-akka-http#13]
Hi, this version is not presented there, the one you can actually find is the experimental one, not the updated version using "0.6.5".

**Comment by dpsoft** [comment]
@thiagoandrade6 the `0.6.5` is in our bintray repository (https://bintray.com/kamon-io/releases)

**Comment by iamthiago** [comment]
`Resolver.bintrayRepo("kamon-io", "releases")`.
This solved the problem! Thanks @dpsoft
