### ISSUE TITLE
With tracing on, latency metrics are not broken out by individual trace

### ISSUE THREAD

**Issue by gmalouf** [kamon-io/kamon-akka-http#21]
Using the traceName directive, for two of our routes, I observe the following behavior.

200/400 responses get grouped a percentile counts in metrics such as 

nutmeg.http_server.ProductDecision_200
nutmeg.http_server.ProductDecision_400

however the latency metrics are not grouped by the trace name (i.e. ProductDecision) but instead are all under the trace category:

nutmeg.trace.elapsed_time.99percentile
nutmeg.trace.elapsed_time.95percentile

shouldn't there be latency metrics for the traces and shouldn't they be under a similar metric path?

**Comment by ivantopo** [comment]
hey @gmalouf!

I think that the metrics are just fine.. it seems like you are looking at this data in Datadog and the kamon-datadog reporter will add a tag with the Entity name.. in this case, for example, you should have a metric named `nutmeg.trace.elapsed_time.99percentile` and there should be a tag `trace:ProductDecision` for that metric. There is a mismatch between how the HttpServerMetrics tool is recording the metrics (by convention in a metric name without tags) and how the trace metrics are reporter.. search for the `trace:ProductDecision` tag and let us know what you find!

**Comment by gmalouf** [comment]
@ivantopo thank you for explaining this - exactly the issue I was running into!  Appreciate the help.
