### ISSUE TITLE
Client request headers are being overridden by kamon headers

### ISSUE THREAD

**Issue by ecyshor** [kamon-io/kamon-akka-http#25]
It seems that the instrumentation for client requests overrides the headers that were passed to the request with the kamon headers, which breaks any expectations for the clients.

The kamon headers should be appended to the already existing headers and not override them.

https://github.com/kamon-io/kamon-akka-http/blob/kamon-1.0/kamon-akka-http/src/main/scala/kamon/akka/http/instrumentation/ClientRequestInstrumentation.scala#L83

**Comment by ivantopo** [comment]
oh, thanks for reporting this! we will fix it asap :)

**Comment by sjoerdmulder** [comment]
@ivantopo PR #26 is ready! Also extended test

**Comment by ivantopo** [comment]
Hey guys, we just published a snapshot containing these changes: `1.0.0-RC8-c453caa2b53b78ac70c5ebb3c06cf20f680899b0`. Once again, thanks! This has been one of (if not the most) quick report/fix cycle ever in Kamon :tada:
