### ISSUE TITLE
[Question] Production readiness fo kamon-akka-http

### ISSUE THREAD

**Issue by PiotrFras** [kamon-io/kamon-akka-http#34]
Hi guys,

> A temporary implementation of the Kamon akka-http module.

I am a bit worried about `temporary implementation` statement in the description. Is the module production-ready? If it is, can we change the description, please?

Many thanks.

**Comment by ivantopo** [comment]
Hey @PiotrFras, thanks for pointing this out!

It was temporary a long time ago when we were not sure whether the instrumentation we had was actually appropriate but that this is definitely not temporary, has been solid for quite some time already and used in production by us and several companies more :), definitely production ready!

I changed the description and cleaned up the readme a bit.

**Comment by PiotrFras** [comment]
Many thanks @ivantopo for clarification.
