### ISSUE TITLE
Safari/WebKit - Invalid UTF-8 sequence in header value

### ISSUE THREAD

**Issue by otobrglez** [kamon-io/kamon-akka-http#35]
Hey!

I've had a very very annoying issue with `kamon-akka-http-2.5` (1.0.0 and 1.0.1) and Safari. We are using akka-http for WebSockets and Safari/WebKit has a bug that if empty header is present in response headers it raises `Invalid UTF-8 sequence in header value` error.

- I've traced the bug down to `kamon-akka-http-2.5`.
- Akka HTTP - `10.0.11`
- Akka - `2.5.11`

```
HTTP/1.1 400 Bad Request
X-B3-TraceId: d93e80a606ef9bb5
X-B3-Sampled: 0
X-B3-ParentSpanId:                                    <-- this
X-B3-SpanId: 968b5f7aeaab956c
Server: akka-http/10.0.11
Date: Sun, 25 Mar 2018 00:06:06 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 34
Via: 1.1 google

Expected WebSocket Upgrade request
```

As you can see from the trace `X-B3-ParentSpanId: ` didn't have any value. After disabling `kamon-akka-http-2.5` in out project it all started working again.

Hope this saves someone out there some gray hair. :)

P.s.: Let me know if I can help you with this thing in any way. 

Cheers!

- Oto

**Comment by jakubmarton** [comment]
I can confirm that we have the same problem as well.

**Comment by acjay** [comment]
Is there a fix? This really nearly cause a major production bug for us, but we were fortunate to catch it in staging.

**Comment by ivantopo** [comment]
Hello there!

Thanks a lot @otobrglez for reporting this and @jakubmarton / @acjay for confirming, this has been just fixed in kamon-core since its a B3 codec issue. Minor release coming soon.

**Comment by jakubmarton** [comment]
Hello awesome, just yesterday I made the similar fix to the one you implemented (by setting custom codec in `kamon.context.codecs.http-headers-keys.span` config)
I am checking every header though. My apologies for not sharing this earlier, maybe it would have saved you some investigation time.

```
class HttpSpanCodec extends SpanCodec.B3 {
  override def encode(context: Context): TextMap = {
...
      putHeaderIfNonempty(carrier, Headers.TraceIdentifier, spanContext.traceID)
      putHeaderIfNonempty(carrier, Headers.SpanIdentifier, spanContext.spanID)
      putHeaderIfNonempty(carrier, Headers.ParentSpanIdentifier, spanContext.parentID)
...
 
  }
  private def putHeaderIfNonEmpty(carrier: TextMap.Default, headerName: String, identifier: Identifier) = {
    val id = identifier.string
    if (!id.isEmpty)
      carrier.put(headerName, urlEncode(id))
  }
```
But I will rather use that bugfix release of kamon-core though :)

**Comment by ivantopo** [comment]
Hey guys! I did publish kamon-core 1.1.1 on Friday with the fix for the above. Sorry for the delay on notifying! 

@jakubmarton that's nice, thanks for sharing! I'll take a close look at which cases could lead to anything other than the parentID being empty and act accordingly, it seems like we could end up doing exactly the same as what you shared :D

**Comment by otobrglez** [comment]
We deployed a new version of our "thing" this morning w/ Kamon 1.1.1. and the bug went away. I wanna thank everybody for the help on this issue. You can probably close this puppy down now. :)
