### ISSUE TITLE
Extract HTTP headers in a case-insensitive way

### ISSUE THREAD

**Issue by thomschke** [kamon-io/kamon-akka-http#39]
According to RFC 7230 and RFC 7540 --> **HTTP/1.1 and HTTP/2 headers are case-insensitive**  (https://stackoverflow.com/a/41169947)

The ServerFlowWrapper has to extract HTTP headers in a case-insensitive way.

see also kamon-io/Kamon#517

**Comment by jatcwang** [comment]
I think this can be closed as it was addressed by https://github.com/kamon-io/kamon-akka-http/pull/38?

**Comment by thomschke** [comment]
LGTM -> but see kamon-io/Kamon#517
