### ISSUE TITLE
2.12 compatible release

### ISSUE THREAD

**Issue by cory-p-oncota** [kamon-io/kamon-akka-http#7]
Need an 0.6.5 compatible release for these first:
```
kamon-akka
kamon-log-reporter
```

I believe the final compatibility matrix would look like this:
```
2.10 - no support
2.11 - 2.4.x/10.0.x
2.12 - 10.0.x
```

**Comment by dpsoft** [comment]
@cory-p-oncota log-reporter done!

**Comment by andresilva** [comment]
I think along with that the `akka-http` dependency should be updated to `"akka-http" % "10.0.1"` and this module should be renamed to `kamon-akka-http` (dropping the experimental).

**Comment by dpsoft** [comment]
done!!!
